<?php

return [
    "ASK_APPEND" => "Are you sure to append this record ?",
    "ASK_MODIFY" => "Are you sure to modify this record ?",
    "ASK_DELETE" => "Are you sure to delete this record ?",
    "ASK_UPDATE" => "Are you sure to update this record ?",
    "ASK_ABANDON" => "Are you sure to abandon any changes to this record ?",
    "ASK_CHANGE" => "Are you sure to change this value ?",
    "ASK_REPLACE" => "Are you sure to replace the existing value with the default value ?",
    "ASK_SAVELAST" => "You leave a work being edited. \n Do you want to save your last work now ?",
    "ASK_SAVEWORK" => "Do you want to save your work ?",
    "ASK_RETURN" => "Return to Main Menu ?",

    "ERR_UNDOLAST"  => "You had close a work being edited. \n Transaction has rollback !",
    "ERR_VERIFY"  => "Please verify your input !",
    "ERR_INSERT"  => "You cannot insert record has been locked by system !",
    "ERR_MODIFY"  => "You cannot modify record has been locked by system !",
    "ERR_UPDATE"  => "You cannot update record has been locked by system !",
    "ERR_DELETE"  => "You cannot delete record has been locked by system !",
    "ERR_VALIDID"  => "This code has already exist",
    "ERR_VALIDREF"  => "Your Reference Number has been used by another user !",
    "ERR_CONFLICT"  => "ID Number has been used by another user",
    "ERR_TRANS"  => "Transaction is failed !",
    "ERR_LOCKED "  => "It has been locked by another user",
    "ERR_RECORD"  => "You cannot modify the same record !",
    "FAIL_UPDATE"  => "Update is failed. \n Transaction has rollback !",
    "FAIL_DELETE"  => "Delete is failed. \n Transaction has rollback !",
    "MSG_SUCCESS"  => "Success !",
    "MSG_FAILED"  => "Failed !",
    "MSG_FOUND"  => "Found !",
    "MSG_ERRUPD "  => "Update error !",
    "MSG_NODETECT"  => "No record detected !",

    //"ERR_CREDENT" => "Invalid credentials",
    // "ERR_CREATE_TOKEN" => "Could not create token",
    // "ERR_EXPIRED_TOKEN" => "Sorry, your token expired",
    // "ERR_INVALID_TOKEN" => "Token Invalid",
    // "ERR_ABSENT_TOKEN" => "Sorry, token not found",
    // "ERR_USER" => "User not found",
    "ERR_CREDENT" => "Email/Password yang dimasukan salah !",
    "ERR_CREATE_TOKEN" => "Tidak dapat membuat token.",
    "ERR_EXPIRED_TOKEN" => "Maaf, Sesi token telah berakhir, silahkan login kembali !",
    "ERR_INVALID_TOKEN" => "Autentikasi token salah.",
    "ERR_ABSENT_TOKEN" => "Maaf, Token tidak dapat ditemukan.",
    "ERR_USER" => "User tidak dapat ditemukan.",

];
